### ISSUE TITLE
List all supported languages by alphabetical order (don't have a first list of most-frequently used languages)

### ISSUE THREAD

**Issue by offray** [Qeole/Enlight#10]
Hi and thanks for this open source extension.

Sometimes I want to see the highlighted source code of a light markup language for documentation published on the web, like AsciiDoc or Markdown, which are supported by highlight.js . There is any way to have them available in the drop down list provided by Enlight?

**Comment by qmonnet** [comment]
Hi and thanks for the feedback!

AsciiDoc and Markdown are both in the drop-down list. Actually, all languages supported by highlight.js are. Could you please check and let me know if you really don't find them?

Please note that for a historical reason (but I should really change that one day...), the languages in the drop-down list are sorted in two consecutive lists in alphabetical order: the first one with the 23 most often used languages, then all other languages. So Markdown is in the first list (15th position) and AsciiDoc below (32nd from top of drop-down menu it seems).

**Comment by Qeole** [comment]
Hi and thanks for the feedback!

AsciiDoc and Markdown are both in the drop-down list. Actually, all languages supported by highlight.js are. Could you please check and let me know if you really don't find them?

Please note that for a historical reason (but I should really change that one day...), the languages in the drop-down list are sorted in two consecutive lists in alphabetical order: the first one with the 23 most often used languages, then all other languages. So Markdown is in the first list (15th position) and AsciiDoc below (32nd from top of drop-down menu it seems).

**Comment by offray** [comment]
Quentin,

Thanks, I can see now the Markdown and AsciiDoc entrances and yes, my
issue is that I was expecting some kind of alphabetical order... so,
maybe the issue is not so much about their presence, but their place.
Following the "principle of least surprise", users should be warn about
this frequency order and let them change it to alphabetical, for example
(choosing alphabetical over use frequency as default could be a way to
deal with such principle).

Cheers,

**Comment by Qeole** [comment]
Agreed. This is on top of my to-do list for this add-on. I'll try to take some time to fix it in the coming days (hopefully) or weeks.

Thanks again for the feedback!

**Comment by Qeole** [comment]
Fixed, I'll push the new version to AMO later tonight or tomorrow.
