### ISSUE TITLE
Version 2.4.9.15 breaks dropdown menu

### ISSUE THREAD

**Issue by Mikaz-fr** [Qeole/Enlight#14]
Release version 2.4.9.15 is much faster to autodetect languages, but when I click the icon the popup is broken and nothing shows up:
![popup](https://user-images.githubusercontent.com/2411679/58461652-730a9f00-8130-11e9-90d2-25e0b4ccb436.png)
This means when I click it the highlighting disappear and I have now way to bring it back.
I could reproduce this behavior on Windows 10 Firefox 62 and Windows 7 Firefox 66 portable.

Let me know if I can somehow help.

**Comment by Qeole** [comment]
Hmm that's not good :(. I can reproduce it on my setup at some occasions, like:

1. Enable autodetection.
2. Open a text file, which gets highlighted.
3. Click button to remove highlighting.
4. Click button again: popup is empty.

But then if I click the button again, I get the popup as expected, so it remains usable (but awkward). Are you experiencing the same, or is there no way to bring the language list back for you?

In either case I agree there's a bug, I'm just trying to assert if we see the same thing.

**Comment by Mikaz-fr** [comment]
No I can't get the popup to normally display the list, no matter how many times I click it. It keel toggling between no popup at all and the empty white one.
Same behavior if I disable the autodetection or enable all possible syntaxes.

**Comment by Qeole** [comment]
That's concerning. Ok thanks, I'll investigate to fix it on my Linux setup, and if it's not enough I'll try to get a hand on a Windows machine somewhere to help debug.

**Comment by Qeole** [comment]
I tried to push a fix, haven't tested on Windows for now. Let me know how it goes.

**Comment by Mikaz-fr** [comment]
Will try once the release is available, or let me know if there is another way to validate the change.

**Comment by Qeole** [comment]
There is at least the following:
1. Disable automatic updates for the add-on.
2. Manually look for update (and apply).
3. Re-enable automatic updates.

(No rush, though :) )

**Comment by Mikaz-fr** [comment]
Ok verified to be working great with version 2.5.9.15.
Thanks again for the quick reaction. Don't forget to make a release for it on Github too :smiley:

**Comment by Qeole** [comment]
Will do :). Awesome, thanks a ton for the report & test!

Fixed with a238df6, closing the issue.
