### ISSUE TITLE
R syntax highlighting breaks at apostrophes inside comments 

### ISSUE THREAD

**Issue by vertesy** [Qeole/Enlight#16]
When you check https://raw.githubusercontent.com/vertesy/CodeAndRoll/master/CodeAndRoll.R
![image](https://user-images.githubusercontent.com/5101911/101834224-5c714080-3b3a-11eb-9256-1518962deb16.png)

you can see that R **syntax highlighting breaks apostrophes inside comments,** particularly bad for roxygen skeletons

**Comment by Qeole** [comment]
Thank you, it seems that the comments are not correctly parsed indeed.
But parsing is not done in the code of the add-on (I mean, by the code I maintain here). It is performed by the library that is embedded, highlight.js, which the add-on loads unchanged. I would encourage you to report the issue [to the relevant project](https://github.com/highlightjs/highlight.js).
