### ISSUE TITLE
Switch from Firefox Add-on SDK to WebExtensions

### ISSUE THREAD

**Issue by Qeole** [Qeole/Enlight#5]
Because Firefox will stop signing new add-ons based on add-on SDK circa April 2017, and will ultimately stop loading these extensions at the end of the same year, Enlight will have to move to WebExtensions framework.

See <https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/> for more information.

**Comment by jalcine** [comment]
This is a blocker for me using it on Nightly.

**Comment by Qeole** [comment]
Yeah, sorry about that. I can't use it either on Dev Edition. I started to work on a new version, but haven't found the time to finish it yet. I'll try to have it ready before Firefox 57 gets stable (13th Nov.), hopefully…
Thanks for the feedback!

**Comment by Qeole** [comment]
@jalcine I pushed the new version some minutes ago! I'll try to push it to AMO now in order to get automatic update for everyone.

**Comment by Qeole** [comment]
Erf sorry, in the end it needs a bit more testing/fixing. I pushed it to AMO and updated on my computer, but automatic highlighting broke some other pages, such as GitHub. I deactivated this version from AMO.

**Comment by Qeole** [comment]
Should be fixed with commit 4d32daa6924046366749b1c0e1898a90494b18d3. Add-on seems to work well, I pushed to AMO again. It's waiting for review, but apparently it's already possible to install it (if you have Dev Edition or Nightly I suppose). AMO platform seems to have somewhat changed recently, and I haven't been following closely.

**Comment by jalcine** [comment]
Thank you @Qeole!

**Comment by Qeole** [comment]
You're welcome, and thank you for the rating :)
